name: SendToServer
version: 1.4
main: it.alessiogta.send4Server.SendToServer
api-version: 1.21.1
author: AlessioGTA
website: https://www.mclegacy.it
commands:
  sendtoserver:
    description: Invia un giocatore a un altro server o apri la GUI
    usage: /sendtoserver <server|gui|reload>
    permission: sendtoserver.use
    aliases: [sts]
permissions:
  sendtoserver.use:
    default: true
  sendtoserver.reload:
    default: op
